name: frontend_server_common
publish_to: none
description: >-
  Frontend server integration code to use for dwds tests. Mimicks flutter code.
environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  file: ^5.1.0
  usage: 3.4.2
  dwds:
    path: ../dwds
